version: '3.0'

services:

  mysql:
    image: mysql
    restart: always
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - ".env"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: captain
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
